[versions]
android-gradle-plugin = "8.6.1"
jreleaser-plugin = "1.19.0"

[libraries]

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser-plugin" }
